

CREATE TABLE promocodes (
  id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  code CHARACTER VARYING(16) NOT NULL,
  type smallint NOT NULL,
  disabled smallint NOT NULL default 0,
 
  details text DEFAULT NULL,
  CONSTRAINT PK_promocodes PRIMARY KEY (id)
)   ;   

CREATE UNIQUE INDEX IF NOT EXISTS IX_promocodes_code
ON promocodes (
  code
);


DELETE  FROM "options" WHERE  optname='version' ;
INSERT INTO "options" (optname, optvalue) values('version','6.10.0');  